version: '3.5'

services:
  time-series-view:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - VIEW_PORT
      - SPRING_PROFILES_ACTIVE
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
      - ELASTIC_CLUSTERNAME
      - ELASTIC_USER
      - ELASTIC_PASSWORD
      - MICROSERVICE_NAME=${UNIT_NAME}-view
      - SPRING_KAFKA_CLIENT-ID={{.Service.Name}}-{{.Task.Slot}}
      - JAVA_OPTS=-Xmx568m -Xms256m
    networks:
      - elastic-net
      - metric-net
      - kafka-net
      - redmic-net
      - traefik-net
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${VIEW_PORT}/api/${UNIT_NAME}/view/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.rule: Host:${PUBLIC_HOSTNAME};PathPrefix:/api/${UNIT_NAME}/view
        traefik.backend: ${UNIT_NAME}-view
        traefik.port: "${VIEW_PORT}"
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '1'
          memory: 768M
        reservations:
          memory: 615M

networks:
  elastic-net:
    name: ${ELASTIC_NET_NAME:-elastic6-net}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    external: true

  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    external: true

  redmic-net:
    name: ${REDMIC_NET_NAME:-redmic-net}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true
