version: '3.5'

services:
  time-series-commands:
    ports:
      - ${COMMANDS_PORT}
    networks:
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${COMMANDS_PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: PathPrefix:/api/${UNIT_NAME}/commands
        traefik.backend: ${UNIT_NAME}-commands
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  traefik-net:
    external: true

volumes:
  commands-vol:
    name: "${UNIT_NAME}-commands-{{.Task.Slot}}-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2
