version: '3.5'

services:
  time-series-commands:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/server/time-series}:${IMAGE_TAG:-latest}
    environment:
      PORT:
      SERVER_PORT: ${PORT}
      OAUTH_CLIENT_ID:
      OAUTH_CLIENT_SECRET:
      MICROSERVICE_NAME: ${UNIT_NAME}-commands
      SPRING_KAFKA_CLIENT-ID:
    networks:
      metric-net:
      kafka-net:
      redmic-net:
      traefik-net:
    volumes:
      - commands-vol:/tmp/kafka
    healthcheck:
      test: wget --spider -S -t 1 http://localhost:${PORT}/api/${UNIT_NAME}/commands/actuator/health
      interval: ${TIME_SERIES_COMMANDS_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${TIME_SERIES_COMMANDS_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${TIME_SERIES_COMMANDS_HEALTHCHECK_RETRIES:-3}
      start_period: ${TIME_SERIES_COMMANDS_HEALTHCHECK_START_PERIOD:-2m}
    deploy:
      mode: replicated
      replicas: ${TIME_SERIES_COMMANDS_REPLICAS:-1}
      labels:
        traefik.frontend.rule: Host:${PUBLIC_HOSTNAME};PathPrefix:/api/${UNIT_NAME}/commands
        traefik.backend: ${UNIT_NAME}-commands
        traefik.port: '${PORT}'
      restart_policy:
        delay: ${TIME_SERIES_COMMANDS_RESTART_DELAY:-15s}
      update_config:
        delay: ${TIME_SERIES_COMMANDS_UPDATE_DELAY:-5m}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true

  redmic-net:
    name: ${REDMIC_NET_NAME:-redmic-net}
    driver: ${REDMIC_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

