version: '3.5'

services:
  time-series-commands:
    environment:
      - JAVA_OPTS=-Xmx768m -Xms256m
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: 1G
            reservations:
              memory: 820M
