version: '3.5'

services:
  time-series-view:
    environment:
      - JAVA_OPTS=-Xmx768m -Xms256m
    ports:
      - target: ${VIEW_PORT}
        published: ${VIEW_PORT}
        mode: host
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 820M
