version: '3.5'

services:
  time-series-commands:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: -Xmx768m -Xms256m
    deploy:
      resources:
        limits:
          cpus: '${TIME_SERIES_COMMANDS_RESOURCES_LIMITS_CPUS:-1}'
          memory: ${TIME_SERIES_COMMANDS_RESOURCES_LIMITS_MEMORY:-1G}
        reservations:
          cpus: '${TIME_SERIES_COMMANDS_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${TIME_SERIES_COMMANDS_RESOURCES_RESERVATIONS_MEMORY:-820M}
